### ISSUE TITLE
handle /devtools/browser endpoint

### ISSUE THREAD

**Issue by paulirish** [wendigo/chrome-protocol-proxy#1]
This is what's used by puppeteer. They connect to the browser endpoint and use Target.sendMessage for nearly all their stuff.

Since `chrome-protocol-proxy` doesnt proxy that endpoint, it doesn't seem possible to use against puppeteer.

As an example I'm trying to use it with https://github.com/GoogleChrome/puppeteer/blob/master/examples/block-images.js but changing the `puppeteer.launch()` line to: `const browser = await puppeteer.connect({browserWSEndpoint: "ws://localhost:9223/devtools/browser/6ad89a71-164e-46a1-8c63-c9e588b0780b"});`

**Comment by wendigo** [comment]
Thx for the issue @paulirish. Will look into that :)

**Comment by wendigo** [comment]
Fixed in v0.3.2 (releasing right now). Checked against example you've provided - frames are being dumped correctly. Thanks for pointing that missing functionality @paulirish
