### ISSUE TITLE
Missing shared dependency

### ISSUE THREAD

**Issue by ghost** [wendigo/chrome-protocol-proxy#4]
The `chrome-protocol-proxy` binary for linux-amd64 depends on `libc.musl-x86_64.so.1`. You don't have it in major distros, so the binary won't run. I had to do `ln -s /lib64/ld-linux-x86_64.so.2 /lib/libc.musl-x86_64.so.1`, after that it seems to work.

**Comment by wendigo** [comment]
Thanks for letting me know @opennota. I will look into it as release process happens on ci/cd environment

**Comment by wendigo** [comment]
Fixed in v0.4.7
